### PR TITLE
add kafka connectors and added tutorials to the documentation repo

### PR DESCRIPTION
**Pull request by RongDu7**

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the work @RongDu7 

Please add a README.md to your folder. You should include
- An explanation of the purpose of the code. (What does it do?)
- The package dependencies.
- The entry point of your code (which I think is "connector example.py")
- There should be no space in the file / folder name.

**Review by Ingabreezy — COMMENTED** [review]
No vulnerabilities detected in the py scripts. Add the README document as instructed then tag me for approval

**Comment by RongDu7** [comment]
@Ingabreezy please review and merge

**Review by kcf-jackson — COMMENTED** [review]
Points 1 and 3 are well addressed. Points 2 and 4 are not. 
- About point 2, there is no pip command to install the required packages (e.g., dotenv requires python-dotenv).
- About point 4, there is a space in "connector example.py".

**Comment by ben-AI-cybersec** [comment]
This was done without consultation with the data warehouse team? Change requests have not been actioned, closing PR

**Pull request closed without merging**
