### PR TITLE
Movenet_player_tracking

### PR DESCRIPTION
**Pull request by Skyithamster**

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the updates. @Skyithamster 

- Please create a subfolder under `Player_Tracking` to contain your jupyter notebook, as your notebook downloads images to the working directory. 
- I understand you are adapting the MoveNet notebook for your application. I suggest that you convert the notebook into two interface functions, one to process image and another to process video, to make it easier for users to use. 
- You did not include the test image and gif you used. Please add them back. 
- At the moment, the updated notebook is not a lot different to the original notebook, and it does not communicate to me your contribution. Substantial revision is needed.

**Comment by Ingabreezy** [comment]
@Skyithamster kindly tag me for merging once required changes have been made

**Comment by Skyithamster** [comment]
@Ingabreezy i have committed the changes

**Review by kcf-jackson — APPROVED** [review]
I confirm all comments have been addressed. 
This is ready for merging. @Ingabreezy @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
This is fine

**Pull request merged**
