### PR TITLE
Pose Estimation and Matching

### PR DESCRIPTION
**Pull request by Aryan9001**
The objective of this project is to develop a pose estimation and matching system using OpenCV that processes real-time camera inputs, video files, and images. The system identifies key points on the human body and compares them with a reference pose, providing a similarity score. The initial focus was on pose estimation, followed by pose matching refinement and optimization for real-time video processing. @kcf-jackson

### CODE REVIEW

**Comment by ben-AI-cybersec** [comment]
@Aryan9001 Please update your PR name and description to something meaningful describing what you've changed.

**Review by kcf-jackson — COMMENTED** [review]
Thanks for the work @Aryan9001

- Please remove '.ipynb_checkpoints' folder.
- Please remove all spaces in the filename and folder name.
- File should not have names "Untitled".
- Please include some descriptions in your .ipynb notebook.
- It's preferred to put all the images and videos into a `data` folder. For videos, if possible, please use a link instead of upload too many videos.
- Please add `README.md` to the folders.
- Please use Markdown files over PDF files for documentation.

**Comment by Aryan9001** [comment]
The Required Changes have been made. @kcf-jackson

**Review by kcf-jackson — APPROVED** [review]
I confirm all previous comments have been addressed.
Ready for merging @Ingabreezy @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
Manually reviewed app.py, and documentation. LGTM

**Pull request merged**
