### PR TITLE
add work for llm development and interfacing with database

### PR DESCRIPTION
**Pull request by sumituiet**
Please review @kcf-jackson

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the work @sumituiet 

- Please remove spaces in the folder name. See the top level README of this repo of the naming convention. 
- Please add a README to the folder. You should mention the intended purpose of each notebook.
- There are hardly any comments / notes in your notebooks. It is unclear what the code is trying to do. Please add brief descriptions to explain the workflow. 
- Please reference `Unsloth` documentation for installation guide, since this package has different installation guidelines for different GPUs.
- Please mention the GPU RAM required to run the notebook. I am testing on GPU: NVIDIA A10. Max memory: 21.988 GB. Platform = Linux, and I am still getting an error about memory.
- Please specify the dependencies of your notebook (e.g. missing dependency `python-dotenv`
- Please add instruction on how to get a HF token.
- I am getting a bunch of errors running these notebooks. When you revise and resubmit, please include screenshots of your teammate successfully running the notebooks before requesting for review.

**Comment by Ingabreezy** [comment]
@sumituiet kindly tag me for approval once the required changes have been made

**Comment by sumituiet** [comment]
@Ingabreezy I did all the required changes and update the api as well please let me know if more information or changes are required.

**Review by kcf-jackson — COMMENTED** [review]
- Points 1,2 are well addressed. Points 3, 4, 5, 6, 7, 8 are not. 
- About point 6, I see that there is an attempt to create a conda environment from 'environment.yml' but the yml file has not been committed.
- If there is difficulty completing some of the items, it suffices to explain what issues you have with them without completing them. Thanks.

**Comment by sumituiet** [comment]
@kcf-jackson and @Ingabreezy  please let me know if additional things are required 

3. add comments to each notebook line and heading 
4. I added the required environment files for this so it shouldn't be an issue but for reference use 

pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

5. i mentioned in the readme.txt 

To run the **Occupancy Query Service** API with the language model, the following hardware specifications are recommended:

- **CPU**: Intel Core i5 or equivalent
- **RAM**: 16 GB
- **GPU**: CUDA-compatible GPU (required for running larger models efficiently)
  - **For 3.5B parameter models**: Minimum 4 GB VRAM
  - **For 8B parameter models**: Minimum 6 GB VRAM
6. added the required environment files
7. in readme.md
8. I added screenshots from my friend Mustafa's system 
with config 
Test system 1:
Device name Mustafa's desktop
Processor Intel(R) Core(TM) Ultra 7 155H 3.80 GHz
Installed RAM 16.0 GB (15.4 GB usable)
Device ID 5B3B4426-CD06-43B4-967E-52FD4CC8B711
Product ID 00342-21229-90146-AAOEM
System type 64-bit operating system, x64-based processor
GPU RTX 4050 (6GB)
image
image
image

**Review by kcf-jackson — APPROVED** [review]
I confirm all previous comments have been addressed. 

Ready for merging @Ingabreezy @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
Excellent work!

**Pull request merged**
