### PR TITLE
PR to Crowd Monitoring

### PR DESCRIPTION
**Pull request by milieureka**
Adjust base on @kcf-jackson comment, all the dependencies and dataset download was added in the sahi_prediction.ipynb. 
Change the repo name
Fix the typo, references in README.md file
@ben-AI-cybersec for merging

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Great work @milieureka 

- Please add the dependency `scikit-image` (and perhaps also `imagecodecs`) back in your first cell.
- Please remove your Roboflow API key from the notebook, and provide instructions how users can get one for themselves.
- Please write down where to get the test data `/content/football-players-detection-10/test/image`.

After you fix the above, tag me for review again. Thanks.

**Comment by kcf-jackson** [comment]
Thanks for the update @milieureka.

Folder organisation:
- You have created the subfolder, but Crowd_Monitoring/Small_detection_YOLO_and_SAHI-2.ipynb is still around, please move that into the subfolder or remove it. 
- Folder name should have no space. Naming conventions are provided in the README.md at the top level of the repo. 

Suggested edits for README.md:
> In computer vision, a small object does not necessarily correspond to small objects in reality; rather, it indicates the object's size in relation to the entire image. This distinction is important, especially in aerial imaging, where objects may appear small because of the camera's distance.

> The small object is a universal problem for various object...

Some typos:
- five fold -> five-fold
- explaination -> explanation
- Morover -> Moreover
- aproach -> approach

You used more than one reference styles in your reference section. The first one uses the abbreviation for the first name, but the other two uses full spelling. Please use one only. 

Please add the following dependencies in your first cell: scikit-image imagecodecs fiftyone

Please state which Python version you are using. 

Please write down where to get the test data /content/football-players-detection-10/test/image or add it manually to the resource folder.

Once you fixed the above, please tag `ben-AI-cybersec` for merging. Thank you.

**Comment by milieureka** [comment]
Adjust base on @kcf-jackson comment, all the dependencies and dataset download was added in the sahi_prediction.ipynb.
Change the repo name
Fix the typo, references in README.md file
@ben-AI-cybersec for merging

**Review by Ingabreezy — COMMENTED** [review]
No vulnerabilities detected

**Comment by Ingabreezy** [comment]
@kcf-jackson have the changes been made as per required?
If so tag me back for merging

**Review by kcf-jackson — APPROVED** [review]
There are still a few typos around. Let's leave that to be fixed in the future. 
@Ingabreezy Please merge and close the PR. Thanks.

**Comment by kcf-jackson** [comment]
@ben-AI-cybersec Items checked. This is ready for merging. Thanks.

**Review by Deamauni1090 — CHANGES_REQUESTED** [review]
@milieureka looks good. Only item to mention is you have a missing python module import error in your model.ipynb notebook:

image

If you are happy with it being submitted like this I'll approve but otherwise you might want to address this.

**Comment by milieureka** [comment]
> @milieureka looks good. Only item to mention is you have a missing python module import error in your model.ipynb notebook:
> 
> image
> 
> If you are happy with it being submitted like this I'll approve but otherwise you might want to address this.

Hi, Im resolve this, delete all unnecessary error codes, thanks for reviewing

**Review by Deamauni1090 — APPROVED** [review]

**Pull request merged**
