### PR TITLE
Fencing 

### PR DESCRIPTION
**Pull request by Brian08p**
@kcf-jackson  Added Fencing folder and files under player tracking

### CODE REVIEW

**Review by Ingabreezy — COMMENTED** [review]
No vulnerabilities detected in the py scripts 
@kcf-jackson need the green light to approve merging

**Comment by kcf-jackson** [comment]
Thanks for the work, @Brian08p .

- For the README.md, 
    - Please add the source of your data and make sure you have the right access. Please check [1](https://www.copyright.com.au/licences-permission/educational-licences/copying-under-education-licence/), [2](https://www.copyright.org.au/browse/book/ACC-Education:-Copyright-Basics-INFO048), and [3](https://www.screenrights.org/screen-audiences/screenrights-licences/australian-educational-licences/) to see if any of these applies.
    - Please add instruction about the entry point (i.e. am I supposed to just use the notebook?) and the commands to run your Python script. 
    - Please include screenshots / videos as demo.
    - Please format the README.md with the Markdown syntax. Use `#` for headers and `-` for list of items.
- About the folder structure, it's preferred you put all the data (.mp4 and .avi) into the `data` folder.
- Please specify the dependencies, either in the notebook or as a requirements.txt or in the README.md.
    - There is the missing dependencies (tensorflow_hub)
- Please add some brief descriptions in the notebook.

**Review by kcf-jackson — CHANGES_REQUESTED** [review]
Most comments have been addressed. 

Please remove the '.ipynb_checkpoints' and '\_\_pycache\_\_' folders, and I'll approve this for merging.

**Comment by Brian08p** [comment]
I’ve addressed the requested changes by removing the .ipynb_checkpoints and __pycache__ folders.

**Review by kcf-jackson — APPROVED** [review]
Checked. Ready for merging @Ingabreezy @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
lgtm

**Pull request merged**
