### PR TITLE
add facial feature extraction

### PR DESCRIPTION
**Pull request by s223503273**

### CODE REVIEW

**Comment by s223503273** [comment]
please review @kcf-jackson

**Comment by kcf-jackson** [comment]
Thanks for the update @s223503273 

- Please remove all spaces in the folder name. See README.md at the top level of the repo for naming convention.
- Please include some test images for testing `meta_data_from_image.ipynb`.
- Please add a README.md and describe the intended purpose of each notebook.
- Please add instructions on how to acquire the data. (I think Kaggle has an API for downloading datasets. Consider adding that into your notebooks).
- Please add descriptions in your notebook to explain the workflow.
- Please show more testing examples at the end of `age_detection.ipynb`.

**Comment by Ingabreezy** [comment]
@s223503273 kindly tag me for approval once the required changes have been made

**Comment by ben-AI-cybersec** [comment]
Requested changes have not been made. Closing PR.

**Pull request closed without merging**
