### PR TITLE
added files for boxingbagdetection, boxingdetection and documentation

### PR DESCRIPTION
**Pull request by senduz**
Added files for Boxing Bag Hit Detection, Boxing Hit Detection and Documentation. 

Work completed by: 
@senduz  Vignesh Senthilnathan

Review required by @kcf-jackson

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the good work. The documentation is well-written. @senduz 

- Please add a reference / link to YOLOv8.
- Please add screenshots / gif / video demo in the documentation.md.
- Please remove your API key from the notebook and provide a brief note how users can get one for themselves.
- Please add more header / description to the notebook.
- Please add the missing testing input videos (or provide a link for download).
- If possible, please try to print the hit statistics on the video.

**Comment by Ingabreezy** [comment]
@senduz kindly tag me for merging once the required changes have been made

**Comment by senduz** [comment]
@Ingabreezy Hi, I have made the changes as asked. Kindly review. Thanks a lot!

**Review by kcf-jackson — APPROVED** [review]
All items have been addressed.
Ready for merging. @Ingabreezy @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
Lovely work, that's creative embedding the webcam javascript into the take_photo function.

**Pull request merged**
