### PR TITLE
add harcascade implementation for face detection with frame id and lo…

### PR DESCRIPTION
**Pull request by abdulahad1487**

### CODE REVIEW

**Review by sumituiet — CHANGES_REQUESTED** [review]
Please run the notebook and add the outputs as well

**Comment by kcf-jackson** [comment]
Thanks for the work. @abdulahad1487 

- 'weights_path' and 'config_path' seem to be missing in `doc.md`.
- For `installation and environment setup`, please provide the actual commands for the installation, e.g. `pip install opencv-python` like you did in `haarcasade.ipynb`.
- For the `face_detection_data.ipynb` notebook
    - Please add the dependencies installation command.
    - There are missing weights file, cfg file, video_url, and the dat files. 
- Please add some basic descriptions in the notebooks. Feel free to reuse some material from your (well-written) `doc.md`.
- In `haarcasade` notebook
    - the extension name in the code is duplicated `.jpg.jpg`.
    - please test your models on more images, one is too few and it also missed one face in the image. You should consider 10-50 images.

**Review by Ingabreezy — COMMENTED** [review]
No security vulnerabilities detected

**Comment by Ingabreezy** [comment]
@abdulahad1487 Kindly tag me for approval once the required changes have been made

**Comment by abdulahad1487** [comment]
> @abdulahad1487 Kindly tag me for approval once the required changes have been made

i have done changes

**Comment by abdulahad1487** [comment]
@Ingabreezy changes done

**Review by sumituiet — APPROVED** [review]

**Review by kcf-jackson — APPROVED** [review]
Point 2 and 4 are not fully addressed. The rest are fine. I will approve this. 

This is ready to be merged. @Ingabreezy and @ben-AI-cybersec

**Review by ben-AI-cybersec — APPROVED** [review]
Poorly written notebooks, but per Jackson's request I will approve

**Pull request merged**
