### PR TITLE
Greyhound tracking

### PR DESCRIPTION
**Pull request by rissicay**
Adding greyhound tracking. Work includes:
- Documentation
- Feature creation notebook
- Training notebooks

Work was completed by
 @rissicay - Chris Abbey
 @plasma141 - MOHITPREET SINGH
 @HarshBhanot7 - Harsh Bhanot

Review required by @kcf-jackson

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the great work @rissicay, @plasma141, @HarshBhanot7

- Please put your folder under the Player_Tracking folder.
- Please provide the testing _input_ video.
- Please include the references / notes regarding the data collection in one of the documentation.
    - https://www.screenrights.org/screen-audiences/screenrights-licences/australian-educational-licences/
    - https://www.copyright.com.au/licences-permission/educational-licences/copying-under-education-licence/
- A suggestion about looping over frames, I recommend setting `verbose=False` in the model evaluation to avoid printing out information every frame. Also, `tqdm` is useful for showing a progress bar, and it is easy to use.
- The local training notebook should also start with installation instruction, e.g. `!pip install -r requirements.txt`
- Finish the TBD items in the 'feature_km_per_hour' notebook and add more descriptions there.

When you are ready, tag @ben-AI-cybersec for merging.

**Review by Ingabreezy — COMMENTED** [review]
No security issues found

**Comment by Ingabreezy** [comment]
@plasma141 kindly tag me for approval once all the required changes have been made

**Comment by plasma141** [comment]
Updated .

Work includes:
 
- Changing directory 
- Adding input video
- Updating training notebooks
- Updating feature notebook
- Adding references to readme


waiting for approval @Ingabreezy

**Review by kcf-jackson — APPROVED** [review]
I confirm all previous comments have been addressed. 
@Ingabreezy @ben-AI-cybersec This is ready to be merged.

**Comment by ben-AI-cybersec** [comment]
local_training notebook points to rissicay's fork of the repo. Missing data.yaml. Other files are fine, so we'll just say this is an example script.

**Review by ben-AI-cybersec — APPROVED** [review]
Other than local_training.ipynb all is fine.

**Pull request merged**
