### PR TITLE
MMA_tracking

### PR DESCRIPTION
**Pull request by BinIsChilling**

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the work @BinIsChilling 

- Please fix the nested folder MMA_tracking/MMA_tracking unless it is intentional. 
- Your Apache license does not have name and year (at the bottom).
- It is recommended to put the test images and video in a folder `data` rather than having all of them at the top level of the project directory. 
- Please add a README.md to the folder explaining what your code was meant to do (e.g. tracking pose in MMA match).
    - Please include the command to install the dependencies (either directly or via the requirements.txt) and how to run the code. 
    - Please add screenshots / gif / video for preview / demo.
- Please remove spaces in the file names. See the README at the top level of the repo for the naming conventions. 
- Please specify the source of the data (and make sure you have the right access). Please check [1](https://www.copyright.com.au/licences-permission/educational-licences/copying-under-education-licence/), [2](https://www.copyright.org.au/browse/book/ACC-Education:-Copyright-Basics-INFO048), and [3](https://www.screenrights.org/screen-audiences/screenrights-licences/australian-educational-licences/) to see if any of these applies.
- Please trim the video and cut off the ads from 4:30 onwards. 
- The inference takes 10+ minutes to finish, please consider adding a progress bar.
- Your `openpose.py` seems to use Qt and I cannot run it on Linux. Please either specify the system requirement (e.g. Windows) or adjust the code to also support Linux (e.g. for file input, the output can be written to disk directly instead of rendering live on the screen).
- Is the model pretrained? If so, please provide a reference to that. If not, please provide the model training code. The model provided is not too good. Find a better one if time permits.

**Comment by Ingabreezy** [comment]
@BinIsChilling kindly tag me for merging once the required changes have been made

**Comment by BinIsChilling** [comment]
just added a improved version and readme file

**Comment by BinIsChilling** [comment]
@Ingabreezy most of the problem addressed. I trimmed thr video to fit the limitation of Github

**Review by ben-AI-cybersec — APPROVED** [review]
This is fine

**Pull request merged**
