### PR TITLE
Added Latest_update_Hisho folder

### PR DESCRIPTION
**Pull request by hishobank**

### CODE REVIEW

**Comment by kcf-jackson** [comment]
Thanks for the good work, @hishobank 

- Please use a more descriptive name than "latest_update" for the folder name.
- There should no space in file name and folder names. See the top level README.md for the naming conventions. 

For the forecasting folder,
- I suggest adding `!pip install pandas prophet matplotlib openpyxl` to the first cell of you visitor notebook.
- Please add back the missing csv data. 

For the warning message folder,
- In your README.md, please mention what the py files were meant to do and which one the entry point is. (Or do I just use the jupyter notebook?)
- Please add missing dependency 'flask', 'pymongo' to your installation commands / guide
- Please test the models on more images and add them too to the README.md.

**Comment by Ingabreezy** [comment]
@hishobank kindly tag me for merging once the required changes have been made

**Comment by hishobank** [comment]
I have updated the codes

**Review by ben-AI-cybersec — APPROVED** [review]
LGTM, excellent work

**Pull request merged**
